export const illiContent = {
  hero: {
    eyebrow: "ILLI · FAMILY CARE COMPANION",
    title: "AI Companion for the Golden Generation",
    subtitle: "Care that feels like family.",
    emphasis: "",
    lead: "ILLI is an AI Life Companion for the Golden Generation — helping older adults stay independent, supported, and connected with family throughout the day.",
    negatives: ["Not a smart speaker.", "Not a medical alert button.", "Not another screen for occasional video calls."],
    closing: "A companion that understands daily life.",
  },
  personalized: {
    eyebrow: "01 · SUPPORTIVE PRESENCE",
    title: "Support that stays with the rhythm of the day.",
    lead: [
      "Most care devices wait for something to go wrong.",
      "ILLI is present throughout everyday life — morning routines, meals, movement, reminders, family messages, shopping, and moments of rest.",
      "It supports independence before a crisis ever begins.",
    ],
    proofs: [
      [
        "24h",
        "Always",
        "Support around the clock.",
        "ILLI is present throughout everyday life, offering reminders, encouragement, and connection at moments that matter most.",
      ],
      [
        "1",
        "Daily ritual",
        "A moment of connection.",
        "Every interaction is a chance to feel cared for and understood, woven into your natural routine.",
      ],
      [
        "0",
        "No burden",
        "Care without intrusion.",
        "ILLI respects your independence. Support arrives gently, not as demands or interruptions.",
      ],
    ],
    vignette: {
      time: "FROM YOUR CARE CIRCLE · 9:30 AM",
      message: "Good morning. Your medication reminder, and the weather looks nice for a walk today.",
      playing: "CARE CHECK-IN",
      track: "Connection moment · Family care",
    },
  },
  philosophy: {
    eyebrow: "· CARE THAT CONNECTS ·",
    title: "It understands the whole person.",
    lead: [
      "Care is not just medication. It is routine, preference, energy, emotion, home, family, and context.",
      "With the user's permission, ILLI learns from My Data to understand how each person lives — then offers support that feels personal, not generic.",
    ],
    circles: [
      ["Your Life", ["Routines", "Preferences", "Wellbeing", "Home context"]],
      ["Your Family", ["Messages", "Memories", "Check-ins", "Emotional connection"]],
      ["Trusted Services", ["Health", "Shopping", "Payments", "Emergency support"]],
    ],
    values: "Understands → Anticipates → Supports → Connects",
  },
  everyday: {
    eyebrow: "02 · MOMENTS OF CARE",
    title: "Stay close, even when you are apart",
    lead: "ILLI helps families become part of everyday life again — not only through scheduled calls, but through small, warm, meaningful moments.",
    quote: "ILLI helps families become part of everyday life again — not only through scheduled calls, but through small, warm, meaningful moments.",
    support: [
      "A morning message.",
      "A reminder from a daughter.",
      "A photo from a grandchild.",
      "A gentle check-in at the right time.",
    ],
    tiles: [
      {
        time: "MORNING",
        title: "Family Morning Call",
        description: "Wake up to personalized messages from family AIs.",
        image: "/images/illi/everyday-morning.png",
        scene: "Family morning call",
      },
      {
        time: "ANYTIME",
        title: "Voice & Memory Messages",
        description: "Hear familiar voices, memories, and updates from loved ones.",
        image: "/images/illi/everyday-voice.png",
        scene: "Voice and memory messages",
      },
      {
        time: "THROUGHOUT DAY",
        title: "Gentle Check-Ins",
        description: "Families can stay connected without making the user feel monitored.",
        image: "/images/illi/everyday-checkins.png",
        scene: "Gentle check-ins",
      },
      {
        time: "EVERY DAY",
        title: "Shared Moments",
        description: "Photos, stories, reminders, and daily rituals become part of the home.",
        image: "/images/illi/everyday-shared.png",
        scene: "Shared moments",
      },
    ],
  },
  moments: {
    eyebrow: "· MORE INDEPENDENCE. MORE PEACE OF MIND ·",
    title: ["More independence.", "More peace of mind"],
    lead: "ILLI is designed to help older adults live confidently while giving families reassurance when it matters. From secure payments and voice-phishing prevention to SOS emergency calls, ILLI adds a layer of practical protection to everyday life.",
    cards: [
      {
        title: "Secure Payments",
        description: "Help reduce the risk of fraud and voice phishing during important transactions.",
        image: "/images/illi/moments-payments.png",
        scene: "Secure payments",
      },
      {
        title: "SOS Emergency Call",
        description: "Connect quickly to emergency support in urgent moments.",
        image: "/images/illi/moments-sos.png",
        scene: "SOS emergency call",
      },
      {
        title: "Smart Shopping",
        description: "Reorder favorite products and essentials when needed.",
        image: "/images/illi/moments-shopping.png",
        scene: "Smart shopping",
      },
      {
        title: "Important Reminders",
        description: "Stay on top of appointments, checklists, medication, and daily tasks.",
        image: "/images/illi/moments-reminders.png",
        scene: "Important reminders",
      },
    ],
  },
  spec: {
    title: "Made to keep close.",
    rows: [
      ["OPERATING SYSTEM", "Powered by Newnal 'aios'"],
      ["DIMENSIONS", "250 mm diameter × 50 mm depth"],
      ["DISPLAY", "2.8-inch circular AMOLED display"],
      ["CONNECTIVITY", "Wi-Fi and Bluetooth connectivity"],
      ["LIGHTING", "360° ambient LED ring with status and care alerts"],
      ["AUDIO", "Full-range speaker system"],
      ["SAFETY FEATURES", "Heat Watch, Move Watch, Meal Check, Fall Check, Walk Safety Check, SOS alert"],
    ],
  },
} as const;
